# Generated by Django 4.0.4 on 2022-04-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='rubcic',
            new_name='rubric',
        ),
    ]
